title: Leila Mae Z. Haboc
logo: /assets/myprofile.jpg
description: Hello! My name is Leila Mae Z. Haboc, currently a 4th year BSIT student at Mabalacat City College, Pampanga. 
description: I have developed my abilities in a variety of IT fields throughout the course of my studies, such as programming languages, SEO program, and networking academy. 
description: This portfolio serves as a summary of my coursework and extracurricular activities. 
description: Join me on this interesting adventure as I continue to explore all the opportunities that the area of Information Technology has to offer. 
description: Together, let us create, code, and create a better digital future!
show_downloads: true
theme: jekyll-theme-minimal
